name: Deploy frontend to Firebase Hosting

on:
  workflow_run:
    workflows: ["Build and Deploy backend Cloud Run]
    branches: [ develop ] #TODO: Change to live
    types:
      - completed

jobs:
  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SA_KEY }}'
          channelId: live
          projectId: '${{ secrets.GCP_PROJECT }}'
