name: Run tests and deploy

on:
  push:
    branches: [ live ]
  pull_request:
    branches: [ live ]

jobs:
  test_build_deploy:
    name: Run tests, build both frontend & backend and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Set up Node 14x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run backend tests
        run: go test ./...

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Build backend
        run: go build

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        with:
          source: "."
          target: ${{ secrets.APP_DIR }}

      - name: Building and restarting web service
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          script: |
            echo "E1 $(printenv REACT_APP_PLAUSIBLE_HOST)"
            echo "E11 $(printenv WILBURX9_ENV)"
            source ~/.profile
            echo "E1 $(printenv REACT_APP_PLAUSIBLE_HOST)"
            echo "E11 $(printenv WILBURX9_ENV)"
            cd '${{ secrets.APP_DIR }}/frontend'
            npm ci
            npm run build
            cd ../
            go build main.go
            sudo /bin/systemctl restart wilburx9
            service wilburx9 status