name: Run tests and deploy to GAE

on:
  push:
    branches: [ live, migrate-away-frm-gcp ]
  pull_request:
    branches: [ live ]

jobs:
  test_build_deploy:
    name: Run tests, build both frontend & backend and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Set up Node 14x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run backend tests
        run: go test ./...

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Build backend
        run: go build

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
        with:
          source: "./"
          target: "/opt/wilburx9"

      - name: Building and restrting web service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /opt/wilburx9/frontend
            npm run build
            cd ../
            go build main.go
            sudo service wilburx9 start
            sudo service wilburx9 status