name: Run test and build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, live ]

jobs:
  test_build_deploy:
    name: Run tests and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Set up Node 14x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run backend tests
        run: go test ./...
        working-directory: backend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Build backend
        run: go build
        working-directory: backend