name: Run tests and update Coveralls

on: pull_request

jobs:
  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'

      - name: Run tests
        working-directory: ./backend
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          go test ./... -v -coverprofile=coverage.out; gcov2lcov -infile=coverage.out -outfile=../backend.lcov; ls -a; cd ..; ls -a

      - name: Coveralls
        if: always()
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.github_token }}
#          path-to-lcov: ./backend.lcov
        run: |
          pwd
          ls -a
          
