name: Run tests and update Coveralls

on: pull_request

jobs:
  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'

      - name: Run tests
        working-directory: ./backend
        run: go test ./... -v -coverprofile=coverage.out

      - name: Convert coverage to lcov
        if: always()
        uses: jandelgado/gcov2lcov-action@v1.0.8
        with:
          infile: coverage.out
          outfile: coverage.lcov
          working-directory: backend

      - name: Coveralls
        if: always()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./backend/coverage.lcov
